### ISSUE TITLE
Vibrate when received notification

### ISSUE THREAD

**Issue by havudk1707** [FMiscia/UnityNotificationManager#1]
Hi Miscia,
Thanks because your plugin very helpful, 
But how to set Vibrate mode when received notification.
Thanks for help.

**Comment by FMiscia** [comment]
Hello and thank you for your interest! 
Unfortunately I don't have the time to work on this. 
I think that you have just to modify the [NotificationHandler](https://github.com/FMiscia/UnityNotificationManager/blob/master/Assets/Scripts/NotificationHandler.cs), adding ` Handheld.Vibrate();` at the line 143.
But I'm not sure!
